server.port=8082
spring.application.name=reactiveSpring
logging.level.org.springframework.r2dbc=trace
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

### For Spring Actuator integration with K8s
### http://localhost:8082/actuator/health/readiness and http://localhost:8082/actuator/health/liveness
management.endpoint.health.probes.enabled=true
management.health.readinessstate.enabled=true
management.health.livenessstate.enabled=true
